MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("clipart_test", )
  STYLE: ("clipart_train",)
SOLVER:
  MAX_ITER: 125180
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-6

OUTPUT_DIR: 'outputs/Adain6_Test'